---

version: '3'
services:
  aai-mock:
    image: registry.gitlab.ics.muni.cz:443/perun/deployment/proxyidp/proxyidp-public-docker-images/ls_aai_mock:2.5.2-broker2.1.10-tomcat9.0-jdk11
    container_name: ls-aai-mock
    volumes:
      - "./configuration/aai-mock:/etc/lsaai-mock"
    ports:
      - '8080:8080'
    networks:
      - lsaaimock
      - my-app-network
  aai-db:
    image: mysql/mysql-server:latest
    container_name: ls-aai-db
    environment:
      MYSQL_ROOT_PASSWORD: 'aaiPass'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'aai'
      MYSQL_USER: 'aai'
      MYSQL_PASSWORD: 'aaiPass'
    volumes:
      - "./scripts/aai-mock.sql:/docker-entrypoint-initdb.d/1.sql"
    # remove this to disable persistent storage
      - "./mysql://var/lib/mysql"
    ports:
      - '3306:3306'
    networks:
      - lsaaimock
      - my-app-network
networks:
  lsaaimock:
  my-app-network:
    external: true
