apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: aai-mock
  name: aai-mock
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: aai-mock
