apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume: aai-mock-claim0
  name: aai-mock-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
